  // Service workbench: research associations do not manufacture passenger routes.
  function download(name,text,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function servicePanel(){const el=$('edInspector'),selected=sel.type==='relation'?MODEL.rels.get(sel.ids[0]):null;
    const ways=sel.type==='way'?sel.ids:selected?.members.filter(x=>x.type==='way').map(x=>x.ref)||[];
    const masters=[...MODEL.rels.values()].filter(r=>r.kind==='route_master');
    el.innerHTML='<h3>Service workbench</h3><p class="note">Research corridors remain provisional. Create only directions and stops supported by evidence. Dates are half-open: start included, end excluded.</p><div class="ed-bar"><button class="btn" id="svNew">New service</button><button class="btn" id="svPhysical">Physical transition</button><button class="btn" id="svEvidence">Track evidence</button></div><ul class="ed-list">'+masters.map(r=>'<li><button class="lnk" data-master="'+r.id+'">'+esc((r.tags.name||r.meta.serviceId)+' · '+r.tags.start_date+'–'+r.tags.end_date)+'</button></li>').join('')+'</ul><div id="svForm"></div>';
    el.querySelectorAll('[data-master]').forEach(b=>b.onclick=()=>{const id=+b.dataset.master;select('relation',[id]);servicePanel();stateForm(MODEL.rels.get(id));});
    $('svNew').onclick=()=>newServiceForm(ways,selected);$('svPhysical').onclick=()=>physicalForm(ways[0]);$('svEvidence').onclick=()=>evidenceForm(ways);
  }
  function field(k,label,value='',area=false){return '<label style="display:block;margin:8px 0;font-size:12px">'+label+(area?'<textarea rows="4"':'<input')+' class="ed-filter" id="sv_'+k+'"'+(area?'>'+esc(value)+'</textarea>':' value="'+esc(value)+'">')+'</label>';}
  const val=k=>$('sv_'+k).value.trim();
  function membersInput(value){return field('members','Ordered members: one per line, “way ID” or “node ID stop/platform”. Repetitions are preserved.',value,true);}
  function parseMembers(){return val('members').split('\n').filter(x=>x.trim()).map(line=>{const [type,ref,...role]=line.trim().split(/\s+/);if(!['node','way'].includes(type)||!Number.isSafeInteger(Number(ref)))throw Error('Use node/way followed by its signed ID');return {type,ref:Number(ref),role:role.join(' ')};});}
  function memberText(r){return r.members.map(x=>x.type+' '+x.ref+(x.role?' '+x.role:'')).join('\n');}
  function sourceInput(value=''){return field('source','Evidence citation (source, page/map, and claim)',value);}
  function newServiceForm(ways,reference){const el=$('svForm');el.innerHTML='<h4>New directional service</h4>'+field('service','Stable service identity')+field('variant','Stable direction identity')+field('name','Service name',reference?.tags.name||'')+field('ref','Official route ref (leave blank if unknown)')+field('operator','Operator')+field('traction','Traction: horse, cable, electric, electric_conduit, electric_overhead, storage_battery, compressed_air, gasoline',reference?.tags['streetcar:traction']||'')+field('start','Start date',reference?.tags.start_date||'')+field('end','End date',reference?.tags.end_date||'')+field('from','From node ID')+field('to','To node ID')+membersInput(ways.map(x=>'way '+x).join('\n'))+sourceInput()+'<label><input type="checkbox" id="svVerified"> Service evidence verified</label><p class="note">An additional direction is added explicitly below; no return route is inferred.</p><button class="btn" id="svCreate">Create service</button>';
    $('svCreate').onclick=()=>{let created;act('Created evidenced service',()=>{const tags={name:val('name'),operator:val('operator'),'streetcar:traction':val('traction')};if(val('ref'))tags.ref=val('ref');created=DCProfile.createService(MODEL,{serviceId:val('service'),line:reference?.line??null,researchIds:reference?.line==null?[]:[lines[reference.line].id],start:val('start'),end:val('end'),tags,status:$('svVerified').checked?'verified':'unresolved',sources:val('source')?[{citation:val('source'),claim:'service'}]:[],variants:[{variantId:val('variant'),fromNode:Number(val('from')),toNode:Number(val('to')),members:parseMembers()}]});});if(created){servicePanel();stateForm(MODEL.rels.get(created));}};
  }
  function stateForm(master){const el=$('svForm');el.innerHTML='<h4>'+esc(master.meta.serviceId)+' · '+esc(master.tags.start_date)+'–'+esc(master.tags.end_date)+'</h4><p class="note">Corrections update this state. A historical transition creates synchronized child states and a new master, including unchanged directions.</p><label>Direction <select class="ed-filter" id="svDirection">'+master.members.map(x=>{const r=MODEL.rels.get(x.ref);return '<option value="'+r.id+'">'+esc(r.meta.variantId)+'</option>';}).join('')+'</select></label><button class="btn" id="svMerge">Merge with next equal state</button><div id="svDirectionForm"></div>';
    $('svMerge').onclick=()=>{act('Merged equal adjacent service states',()=>{const next=[...MODEL.rels.values()].find(r=>r.kind==='route_master'&&r.meta?.serviceId===master.meta.serviceId&&r.tags.start_date===master.tags.end_date);if(!next)throw Error('No adjacent next state');DCProfile.mergeStates(MODEL,master.id,next.id);});servicePanel();};const draw=()=>{const r=MODEL.rels.get(+$('svDirection').value);$('svDirectionForm').innerHTML=field('variant','Direction identity',r.meta.variantId)+field('boundary','Historical transition date (blank = correction)')+field('from','From node ID',r.meta.fromNode)+field('to','To node ID',r.meta.toNode)+field('name','Name',r.tags.name||'')+field('operator','Operator',r.tags.operator||'')+field('ref','Official ref',r.tags.ref||'')+field('traction','Traction',r.tags['streetcar:traction']||'')+membersInput(memberText(r))+sourceInput(r.meta.sources?.map(x=>x.citation).join('; ')||'')+'<label><input type="checkbox" id="svVerified" '+(r.meta.status==='verified'?'checked':'')+'> Service evidence verified</label><div class="ed-bar"><button class="btn" id="svUpdate">Apply direction</button><button class="btn" id="svAddDirection">Add evidenced direction to this state</button></div>';
      const patch=()=>({members:parseMembers(),tags:{name:val('name'),operator:val('operator'),ref:val('ref'),'streetcar:traction':val('traction')},meta:{variantId:val('variant'),fromNode:Number(val('from')),toNode:Number(val('to')),status:$('svVerified').checked?'verified':'unresolved',sources:val('source')?[{citation:val('source'),claim:'service'}]:[]}});
      $('svUpdate').onclick=()=>{let next;act(val('boundary')?'Historical service transition':'Corrected service state',()=>{const p=patch();if(val('boundary'))next=DCProfile.transition(MODEL,master.id,val('boundary'),r.meta.variantId,p);else{Object.assign(r.tags,p.tags);Object.assign(r.meta,p.meta);r.members=p.members;DCProfile.path(MODEL,r);}});servicePanel();if(MODEL.rels.has(next||master.id))stateForm(MODEL.rels.get(next||master.id));};
      $('svAddDirection').onclick=()=>{act('Added explicit service direction',()=>{const p=patch();if(master.members.some(x=>MODEL.rels.get(x.ref).meta.variantId===p.meta.variantId))throw Error('Choose a new direction identity');const rid=newId('relation'),q={...JSON.parse(JSON.stringify(r)),id:rid,members:p.members,tags:{...r.tags,...p.tags},meta:{...r.meta,...p.meta}};DCProfile.path(MODEL,q);MODEL.rels.set(rid,q);master.members.push({type:'relation',ref:rid,role:''});});servicePanel();stateForm(MODEL.rels.get(master.id));};};$('svDirection').onchange=draw;draw();
  }
  function physicalForm(wid){$('svForm').innerHTML='<h4>Physical track transition</h4><p class="note">For a real historical change, split the physical state and all dependent services at the same date. Ordinary map editing records a correction.</p>'+field('way','Way ID',wid||'')+field('boundary','Transition date')+field('key','Changed physical tag (e.g. electrified)')+field('value','New value')+field('nodes','New geometry node IDs (optional, in track order; draw evidenced geometry first)')+sourceInput()+'<button class="btn" id="svPhysicalApply">Split physical state</button>';$('svPhysicalApply').onclick=()=>{act('Split physical track state',()=>{if(!val('source'))throw Error('Provide transition evidence');DCProfile.physicalTransition(MODEL,Number(val('way')),val('boundary'),{tags:val('key')?{[val('key')]:val('value')}:{},meta:{sources:[{citation:val('source'),claim:'physical transition'}]},...(val('nodes')?{nodes:val('nodes').split(/\s+/).map(Number)}:{})});});servicePanel();};}
  function evidenceForm(ways){$('svForm').innerHTML='<h4>Track provenance</h4>'+field('ways','Signed way IDs',ways.join(' '))+sourceInput()+'<label><input type="checkbox" id="svIndependent"> Geometry independently retraced from this source</label><br><label><input type="checkbox" id="svGauge"> Citation establishes the tagged gauge</label><p class="note">Source entry alone does not remove inherited OSM geometry restrictions. Confirm retracing only after completing it.</p><button class="btn" id="svEvidenceApply">Record evidence</button>';$('svEvidenceApply').onclick=()=>act('Recorded track evidence',()=>{if(!val('source'))throw Error('Evidence citation required');for(const wid of val('ways').split(/\s+/).map(Number)){const w=MODEL.ways.get(wid);if(!w)throw Error('Unknown way '+wid);w.meta={...w.meta,geometryStatus:$('svIndependent').checked?'independent':w.meta?.geometryStatus||'osm-derived',gaugeEvidence:$('svGauge').checked,sources:[...(w.meta?.sources||[]),{citation:val('source'),claim:'geometry/gauge'}]};}});}
  function exportPanel(){const el=$('edInspector');el.innerHTML='<h3>Export project</h3><p class="note">Working archive retains unresolved records, evidence and research links. Strict XML contains selected services and their complete dependency graph. Snapshot selects states active on the exact date and omits chronology relations.</p><div class="ed-bar"><button class="btn" id="exArchive">Working archive</button><button class="btn" id="exWorking">Working XML</button><button class="btn" id="exLegacy">Recover older browser draft</button></div>'+field('services','Service identities (comma separated)')+field('at','Snapshot date','1900-01-01')+'<label><input type="checkbox" id="exPublication"> Require publication readiness</label><div class="ed-bar"><button class="btn" id="exTemporal">Strict temporal XML</button><button class="btn" id="exSnapshot">Snapshot XML</button></div><label>Import working archive <input type="file" id="exImport" accept=".json"></label><pre id="exResult" style="white-space:pre-wrap;font-size:12px"></pre>';
    $('exLegacy').onclick=()=>{const old=localStorage.getItem('dcsc-model-v1');if(!old){$('exResult').textContent='No older browser draft was found.';return;}download('dcsc-original-browser-draft.json',old);$('exResult').textContent='Original draft downloaded unchanged. Import that file explicitly to replace the current project with its migrated contents.';};$('exArchive').onclick=()=>download('dcsc-project-v2.json',snapshot());$('exWorking').onclick=()=>download('dcsc-working.osm',DCProfile.xml(MODEL),'application/xml');
    const run=mode=>{try{const out=DCProfile.exportProfile(MODEL,{mode,serviceIds:val('services').split(',').map(x=>x.trim()).filter(Boolean),at:val('at'),publication:$('exPublication').checked});download('dcsc-'+mode+'.osm',out.xml,'application/xml');download('dcsc-'+mode+'-manifest.json',JSON.stringify(out.manifest,null,2));$('exResult').textContent=JSON.stringify(out.manifest,null,2);}catch(e){$('exResult').textContent='Export blocked: '+e.message;}};$('exTemporal').onclick=()=>run('temporal');$('exSnapshot').onclick=()=>run('snapshot');$('exImport').onchange=async e=>{const file=e.target.files[0];if(file){const text=await file.text();act('Imported working archive',()=>restore(text));}};
  }
