/* Run with npm install --no-save playwright; optional CHROMIUM_PATH. */
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');await page.waitForFunction(()=>!!window.DCStreetcars);assert.deepEqual(await page.evaluate(()=>['nodes','ways','rels'].map(k=>DCStreetcars.model[k].size)),[1578,381,277]);await page.click('#editToggle');
const track=await page.evaluate(()=>{const w=[...DCStreetcars.model.ways.values()].find(w=>DCProfile.number(w.tags.start_date)<1900&&DCProfile.number(w.tags.end_date)>1940&&w.nodes[0]!==w.nodes.at(-1));DCStreetcars.editor.select('way',[w.id]);return {id:w.id,from:w.nodes[0],to:w.nodes.at(-1)};});
await page.click('#edServices');await page.click('#svNew');for(const [key,value]of Object.entries({service:'browser-test',variant:'out',name:'Test service',start:'1900',end:'1940',from:String(track.from),to:String(track.to),source:'Fixture only — do not publish'}))await page.fill('#sv_'+key,value);await page.click('#svCreate');assert.equal(await page.evaluate(()=>DCStreetcars.model.rels.size),280);
await page.fill('#sv_boundary','1930-04-06');await page.fill('#sv_operator','Changed operator');await page.click('#svUpdate');assert.equal(await page.evaluate(()=>DCStreetcars.model.rels.size),282);
await page.click('#edUndo');assert.equal(await page.evaluate(()=>DCStreetcars.model.rels.size),280);await page.click('#edRedo');assert.equal(await page.evaluate(()=>DCStreetcars.model.rels.size),282);
await page.reload();await page.waitForFunction(()=>!!window.DCStreetcars);assert.equal(await page.evaluate(()=>DCStreetcars.model.rels.size),282);await page.click('#editToggle');await page.click('#edExport');await page.fill('#sv_services','browser-test');await page.fill('#sv_at','1930-04-06');const download=page.waitForEvent('download');await page.click('#exSnapshot');await download;assert.match(await page.textContent('#exResult'),/"relations": 2/);
await page.check('#exPublication');await page.click('#exTemporal');assert.match(await page.textContent('#exResult'),/Export blocked/);
await page.click('#edServices');await page.screenshot({path:'dc-streetcars/tests/browser.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Browser checks passed: baseline, service form, transition, undo/redo, reload, snapshot, publication gate.');await browser.close();})();
