const test=require('node:test'),assert=require('node:assert/strict'),P=require('../temporal');
function model(){const m={nodes:new Map(),ways:new Map(),rels:new Map(),meta:{}};for(let n=1;n<=4;n++)m.nodes.set(-n,{id:-n,lat:38+n/100,lon:-77,tags:{}});m.ways.set(-1,{id:-1,nodes:[-1,-2,-3],tags:{railway:'tram',start_date:'1862',end_date:'1963'},meta:{geometryStatus:'osm-derived',sources:[]}});m.ways.set(-2,{id:-2,nodes:[-3,-4],tags:{railway:'tram',start_date:'1862',end_date:'1963'},meta:{geometryStatus:'osm-derived',sources:[]}});return m;}
function service(m,both=false){return P.createService(m,{serviceId:'test',start:'1900',end:'1962',tags:{name:'Test','streetcar:traction':'electric'},status:'verified',sources:[{citation:'historic map',claim:'service'}],variants:[{variantId:'out',fromNode:-1,toNode:-4,members:[{type:'way',ref:-1,role:''},{type:'way',ref:-2,role:''}]},...(both?[{variantId:'back',fromNode:-4,toNode:-1,members:[{type:'way',ref:-2,role:''},{type:'way',ref:-1,role:''}]}]:[])]});}
test('valid calendar dates and retained precision',()=>{assert.equal(P.date('1900-02').precision,'month');assert.throws(()=>P.date('1900-02-29'));assert.doesNotThrow(()=>P.date('1904-02-29'));assert.throws(()=>P.date('1900-13'));assert(P.number('1900-06-30')>1900);assert(P.edtf('[1890?,1892~]'));assert(P.edtf('1890/..'));assert(!P.edtf('1900-02-30?'));});
test('half-open interval excludes terminal boundary',()=>{const o={tags:{start_date:'1900-05',end_date:'1901'}};assert(!P.active(o,'1900-04-30'));assert(P.active(o,'1900-05-01'));assert(!P.active(o,'1901'));});
test('service creates only explicit directional variant',()=>{const m=model(),id=service(m);assert.equal(m.rels.get(id).members.length,1);assert.equal(m.rels.size,3);assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);});
test('transition clones unchanged directions and synchronizes complete state',()=>{const m=model(),id=service(m,true),next=P.transition(m,id,'1930-04-06','out',{tags:{operator:'New company'}});assert.equal(m.rels.get(next).members.length,2);for(const x of m.rels.get(next).members)assert.equal(m.rels.get(x.ref).tags.start_date,'1930-04-06');assert.equal(m.rels.get(id).tags.end_date,'1930-04-06');assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);const ch=[...m.rels.values()].find(x=>x.kind==='chronology');assert.equal(ch.members.length,2);});
test('failed transition is atomic',()=>{const m=model(),id=service(m),before=JSON.stringify(P.archive(m));assert.throws(()=>P.transition(m,id,'1930','out',{members:[{type:'way',ref:-2,role:''}]}));assert.equal(JSON.stringify(P.archive(m)),before);});
test('spatial split preserves reverse directions and all repeated occurrences',()=>{const m=model(),id=service(m,true),newId=P.splitWay(m,-1,-2);const master=m.rels.get(id),out=m.rels.get(master.members[0].ref),back=m.rels.get(master.members[1].ref);assert.deepEqual(out.members.map(x=>x.ref),[-1,newId,-2]);assert.deepEqual(back.members.map(x=>x.ref),[-2,newId,-1]);assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);const r={id:-90,kind:'route',line:0,tags:{},members:[{type:'way',ref:newId,role:''},{type:'way',ref:newId,role:''}]};m.rels.set(r.id,r);const n=m.ways.get(newId).nodes;assert.equal(n.length,2);});
test('combine refuses unpaired membership rather than deleting a repeated occurrence',()=>{const m=model();m.rels.set(-1,{id:-1,tags:{},members:[{type:'way',ref:-1,role:''}]});assert.throws(()=>P.combineWays(m,-1,-2,-3));assert(m.ways.has(-2));});
test('snapshot exports complete active graph without chronology',()=>{const m=model(),id=service(m);P.transition(m,id,'1930','out',{tags:{operator:'new'}});const out=P.exportProfile(m,{mode:'snapshot',serviceIds:['test'],at:'1930'});assert.equal(out.manifest.counts.relations,2);assert(!out.xml.includes('chronology'));assert(out.xml.includes('lat="'));assert(out.xml.includes('ref="-1"'));assert.equal(out.manifest.publicationReady,false);assert.throws(()=>P.exportProfile(m,{mode:'snapshot',serviceIds:['test'],at:'1962'}));assert.throws(()=>P.exportProfile(m,{serviceIds:['test'],publication:true}));});
test('strict scope does not silently export provisional corridors',()=>{const m=model();assert.throws(()=>P.exportProfile(m,{serviceIds:['L01']}));assert.throws(()=>P.exportProfile(m,{serviceIds:[]}));});
test('archive roundtrip retains evidence metadata, members, identities and precision',()=>{const m=model();service(m,true);const a=P.archive(m),t={};P.restore(t,a);assert.deepEqual(P.archive(t),a);const bad=JSON.parse(JSON.stringify(a));bad.w[0][1].push(-999);assert.throws(()=>P.restore(t,bad));assert.deepEqual(P.archive(t),a);});
test('semantic equality retains order, roles, repetitions and provenance',()=>{const m=model(),id=service(m),r=m.rels.get(m.rels.get(id).members[0].ref),q=JSON.parse(JSON.stringify(r));q.members.reverse();assert.notEqual(P.stateKey(r),P.stateKey(q));q.members=r.members;q.tags['start_date:edtf']='1900?';assert.notEqual(P.stateKey(r),P.stateKey(q));});
test('physical transition updates service dependencies',()=>{const m=model();service(m);const wid=P.physicalTransition(m,-1,'1930',{tags:{electrified:'contact_line'}});assert.equal(m.ways.get(-1).tags.end_date,'1930');assert.equal(m.ways.get(wid).tags.start_date,'1930');const later=[...m.rels.values()].find(r=>r.kind==='route'&&r.tags.start_date==='1930');assert(later.members.some(x=>x.ref===wid));assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);});
test('diamond rejects a turn while preserving geometric connection',()=>{const m=model();m.nodes.get(-3).tags.railway='railway_crossing';m.nodes.get(-4).lon=-76.9;assert.throws(()=>service(m));assert.equal(m.rels.size,0);});
test('split updates every repeated occurrence in an out-and-back route',()=>{const m=model();P.createService(m,{serviceId:'loop',start:'1900',end:'1940',variants:[{variantId:'round',fromNode:-1,toNode:-1,members:[-1,-2,-2,-1].map(ref=>({type:'way',ref,role:''}))}]});const q=P.splitWay(m,-1,-2),r=[...m.rels.values()].find(r=>r.kind==='route');assert.deepEqual(r.members.map(x=>x.ref),[-1,q,-2,-2,q,-1]);assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);});
test('physical transition synchronizes multiple directions once',()=>{const m=model();service(m,true);P.physicalTransition(m,-1,'1930',{tags:{electrified:'contact_line'}});assert.equal([...m.rels.values()].filter(r=>r.kind==='route_master').length,2);assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);});
test('adjacent equal service states merge while preserving direction order',()=>{const m=model(),first=service(m,true),second=P.transition(m,first,'1930','out',{});P.mergeStates(m,first,second);assert.equal(m.rels.size,4);assert.equal(m.rels.get(first).tags.end_date,'1962');assert.equal(P.validate(m).filter(x=>x.sev==='error').length,0);});
test('service merge refuses changed direction semantics',()=>{const m=model(),first=service(m),second=P.transition(m,first,'1930','out',{tags:{operator:'other'}}),before=JSON.stringify(P.archive(m));assert.throws(()=>P.mergeStates(m,first,second));assert.equal(JSON.stringify(P.archive(m)),before);});
test('crossing review respects interval overlap and grade separation',()=>{const m=model();m.nodes.get(-1).lat=0;m.nodes.get(-1).lon=0;m.nodes.get(-2).lat=1;m.nodes.get(-2).lon=1;m.nodes.get(-3).lat=0;m.nodes.get(-3).lon=1;m.nodes.get(-4).lat=1;m.nodes.get(-4).lon=0;m.ways.get(-1).nodes=[-1,-2];assert.equal(P.crossings(m).length,1);m.ways.get(-2).tags.start_date='1963';m.ways.get(-2).tags.end_date='1970';assert.equal(P.crossings(m).length,0);m.ways.get(-2).tags.start_date='1900';m.ways.get(-2).tags.layer='1';assert.equal(P.crossings(m).length,0);});
test('stop order and blank PTv2 way roles are enforced',()=>{const m=model();assert.throws(()=>P.createService(m,{serviceId:'bad',start:'1900',end:'1940',variants:[{variantId:'one',fromNode:-1,toNode:-4,members:[{type:'node',ref:-4,role:'stop'},{type:'node',ref:-1,role:'stop'},{type:'way',ref:-1,role:''},{type:'way',ref:-2,role:''}]}]}));assert.equal(m.rels.size,0);});
test('migration preserves Claude coordinates, physical IDs, topology and ordered research memberships',()=>{const fs=require('fs'),path=require('path'),a=JSON.parse(fs.readFileSync(path.join(__dirname,'../legacy/dcsc-draft-20260930.json'))),b=JSON.parse(fs.readFileSync(path.join(__dirname,'../exports/dcsc-project-v2.json')));assert.deepEqual(b.n.map(x=>x.slice(0,4)),a.n);assert.deepEqual(b.w.map(x=>x.slice(0,4)),a.w);for(let i=0;i<a.r.length;i++){assert.equal(b.r[i][0],a.r[i][0]);assert.deepEqual(b.r[i][4],a.r[i][4]);for(const [k,v]of Object.entries(a.r[i][3]))assert.equal(b.r[i][3][k],v);assert.equal(b.r[i][5].status,'provisional');}assert.deepEqual([b.n.length,b.w.length,b.r.length],[1578,381,277]);});
test('physical transition preserves provisional research state and splits its chronology references',()=>{const m=model();m.rels.set(-1,{id:-1,kind:'route',line:0,tags:{type:'route',route:'tram',start_date:'1900',end_date:'1940'},members:[{type:'way',ref:-1,role:''}],meta:{status:'provisional',researchIds:['L01']}});m.rels.set(-2,{id:-2,kind:'chronology',line:0,tags:{type:'chronology',start_date:'1900',end_date:'1940'},members:[{type:'relation',ref:-1,role:''}],meta:{status:'provisional'}});const wid=P.physicalTransition(m,-1,'1920-05',{tags:{electrified:'contact_line'}});assert.equal(m.rels.get(-2).members.length,2);const later=[...m.rels.values()].find(r=>r.kind==='route'&&r.tags.start_date==='1920-05');assert.equal(later.meta.status,'provisional');assert.equal(later.members[0].ref,wid);assert(!later.tags['public_transport:version']);});
test('invalid historical geometry change rolls back dependent states',()=>{const m=model();service(m);const before=JSON.stringify(P.archive(m));assert.throws(()=>P.physicalTransition(m,-1,'1930',{nodes:[-1,-999,-3]}));assert.equal(JSON.stringify(P.archive(m)),before);});
